<?php
  include "../../config.inc.php"; include "../../lib.inc.php";
  include "../../login_check.inc.php"; // ログインチェック

  $y =   $_GET["y"];
  $m =   $_GET["m"];
  $id =   $_GET["id"];

  





  if ($login && $admin_sign == 't') {
    // データ準備
    if (is_numeric($y) && is_numeric($m) && checkdate($m,1,$y)) {
      // modify by nanbuwks 20111122
      //$firststamp = mktime(0, 0, 0, $m, 1, $y);
      if ( !is_numeric($d)) {
        $d = 1;
      }
    } else {
      // modify by nanbuwks 20111122
      //$m = date("m",time()+86400*6);
      //$y = date("Y",time()+86400*6);
      //$firststamp = mktime(0, 0, 0, $m, 1, $y);
      $d = date("d",time());
      $m = date("m",time());
      $y = date("Y",time());
    }
    // add by nanbuwks 20111122
    $limitDay=21;
    if ( $limitDay <=  $d )
       {
           $startY = date("Y",mktime(0,0,0,$m,$limitDay,$y));
           $startM = date("m",mktime(0,0,0,$m,$limitDay,$y));
           $nenDo  = date("Y",mktime(0,0,0,$m+1,$limitDay,$y));
           $gatuDo = date("m",mktime(0,0,0,$m+1,$limitDay,$y));
        } else {
           $startY = date("Y",mktime(0,0,0,$m-1,$limitDay,$y));
           $startM = date("m",mktime(0,0,0,$m-1,$limitDay,$y));
           $nenDo  = date("Y",mktime(0,0,0,$m,$limitDay,$y));
           $gatuDo = date("m",mktime(0,0,0,$m,$limitDay,$y));
        }
    $firststamp = mktime(0, 0, 0, $startM, $limitDay, $startY);
    $dayCount = date("d",mktime(0,0,0,$startM+1,0,$y)); // start from 0

    }
  // modify by nanbuwks 20111224,20120111,20120516
  //  $nextM=$startM+1;
  // ダウンロードテーブルオープン
  // $sql="select user_id as id,datefrom,note,schedule_kind.value as value from schedule_kind,schedules where schedules.kind LIKE to_char(schedule_kind.key ,'FM9') and datefrom >= '".$startY."-".$startM."-".$limitDay."' and datefrom < '".$startY."-".$startM+1."-".$limitDay."';";
//  $sql="select user_id as id,datefrom,note,schedule_kind.value as value from schedule_kind,schedules where schedules.kind LIKE to_char(schedule_kind.key ,'FM9') and datefrom >= '".$startY."-".$startM."-".$limitDay."' and datefrom < date  '".$startY."-".$startM."-".$limitDay."'+ interval '1 months' ;";
  $sql="select user_id as id,datefrom,note,schedule_kind.value as value,日付
    from schedule_kind,schedules,
         ( SELECT  '".$startY."-".$startM."-".$limitDay."'::date + serial.arr AS 日付 FROM  GENERATE_SERIES(0,".$dayCount.") serial(arr)) AS schedule_calender
    where
         schedules.kind LIKE to_char(schedule_kind.key ,'FM9')
         AND 日付>=datefrom and 日付<=dateto";


//  $sql = "SELECT * FROM users_duty WHERE user_id='".$id."' AND workdate>='".date("Y-m-d",$firststamp)."' AND workdate<='".date("Y-m-d",$laststamp)."' ORDER BY workdate";
//  echo $sql;
//  exit(0);


  $res = pg_query($conn,$sql);
  $cnt = pg_num_rows($res);

  // 件数確認
  if ($cnt<1) {
    $MES[] = "データ未登録";
  }

  // エラー処理
  if (sizeof($MES)>0) {
    header("HTTP/1.1 404 Not Found");
  } else {
    // ヘッダー出力
//    header("Content-Type: application/octet-stream\n"); 
    header("Content-Type: application/download"); 
    header("Content-Disposition: attachment; filename=\"schedule.csv\""); 
    header("Content-Disposition: filename=\"schedule.csv\""); 
    header("Content-Description: Generated Data");
    header("Content-Transfer-Encoding: binary"); 
  // 2011-05-16 ,20111122 modity nanbuwks
  //  print euc2sjis('"日付","出社時刻","退社時刻","外出時刻","戻り時刻","コメント","作成日時","更新日時"'."\n");
    print utf2sjis('"ID","日付","スケジュール区分","スケジュールコメント"'."\n");
    for ($i=0;$i<$cnt;$i++) {
      $row = pg_fetch_array($res,$i);
//    modify by nanbuwks 20111124      
//      print '"'.date("Y/m/d",date2timestamp($row["workdate"])).'",';
      print $row["id"].",";
//    modify by nanbuwks 20120516      
//      if ($row["datefrom"]!="") {
//        print '"'.$row["datefrom"].'",';
      if ($row["日付"]!="") {
        print '"'.$row["日付"].'",';
      } else {
        print ',';
      }
      if ($row["value"]!="") {
        print ('"'.utf2sjis($row["value"]).'",');
      } else {
        print ',';
      }
      if ($row["note"]!="") {
        print '"'.utf2sjis($row["note"]).'"'."\n";
      } else {
        print ''."\n";
      }
    }
  }
?>
