<?php
  include "../../config.inc.php"; include "../../lib.inc.php";
	
	if (!empty($_GET["y"])) {
		$headertext .= "Set-Cookie: log_y=".$_GET["y"]."; path=/;\n";
 // add by nanbuwks 20111124
		$y = $_GET["y"];
	} else {
		$y = $_COOKIE["log_y"];
	}
	if (!empty($_GET["m"])) {
		$headertext .= "Set-Cookie: log_m=".$_GET["m"]."; path=/;\n";
 // add by nanbuwks 20111124
		$m = $_GET["m"];
	} else {
		$m = $_COOKIE["log_m"];
	}
  // modify by nanbuwks 20111122
         // $firststamp = mktime(0, 0, 0, $m, 1, $y);
	if (is_numeric($y) && is_numeric($m) && checkdate($m,1,$y)) {
          if ( !is_numeric($d)) {
                $d = $limitDay;
		$m = date("m",time());
		$y = date("Y",time());
          }
	} else {
		$d = date("d",time());
		$m = date("m",time());
		$y = date("Y",time());
	}

 // add by nanbuwks 20111124
    $limitDay=21;
    if ( $limitDay <  $d )
       {
           $startY = date("Y",mktime(0,0,0,$m,$limitDay,$y));
           $startM = date("m",mktime(0,0,0,$m,$limitDay,$y));
           $nenDo  = date("Y",mktime(0,0,0,$m+1,$limitDay,$y));
           $gatuDo = date("m",mktime(0,0,0,$m+1,$limitDay,$y));
        } else {
           $startY = date("Y",mktime(0,0,0,$m-1,$limitDay,$y));
           $startM = date("m",mktime(0,0,0,$m-1,$limitDay,$y));
           $nenDo  = date("Y",mktime(0,0,0,$m,$limitDay,$y));
           $gatuDo = date("m",mktime(0,0,0,$m,$limitDay,$y));
        }

	if (is_numeric($y) && is_numeric($m) && checkdate($m,1,$y)) {
        $firststamp = mktime(0, 0, 0, $startM, $limitDay, $startY);
	
	$laststamp = mktime(0, 0, 0, $startM+1, $limitDay-1, $startY);
        $by = date("Y",mktime(0, 0, 0, $startM-1, $limitDay, $startY));	
        $bm = date("m",mktime(0, 0, 0, $startM-1, $limitDay, $startY));	
        $ny = date("Y",mktime(0, 0, 0, $startM+1, $limitDay, $startY));	
        $nm = date("m",mktime(0, 0, 0, $startM+1, $limitDay, $startY));	
	$rows = 9;
	$p = $_REQUEST["p"];
	if ($p=="") $p = 1;


	
	//現在行(1〜rowcount)
	if($rowpos<1) { $rowpos = 1; }
	
	// リンク用テキストの設定
	$linktext  = "<A HREF=\"../../\" CLASS=\"BAR\">トップページ</A> &gt; ";
	$linktext .= "<A HREF=\"../\" CLASS=\"BAR\">管理者メニュー</A> &gt; ";
	$linktext .= "<FONT COLOR=#FFFF00>勤務ログ</FONT> ";
	
	// ヘッダ表示
	$notable = true;
	include ("../../header.inc.php"); include ("../menu.inc.php");
	
	if ($login) {
		if ($admin_sign != 't') {
			$MES[] = "本機能は管理者のみ利用することができます。";
		} else {
			## スケジュール抽出
			$sql = "SELECT user_id,workdate,startstamp,endstamp,goesstamp,backstamp FROM users_duty WHERE ";
			$sql .= "workdate>='".date("Y-m-d",$firststamp)."' AND workdate<='".date("Y-m-d",$laststamp)."'";
			$sql .= " ORDER BY user_id";
			$res = pg_query($conn,$sql);
			$cnt = pg_num_rows($res);
			if ($cnt>0) {
				for ($i=0;$i<$cnt;$i++) {
					$row = pg_fetch_array($res,$i);
					
					$arr_seqno[$row["user_id"]] = get_first("users","seqno","id='".$row["user_id"]."'",0);
					$arr_user[$row["user_id"]] += 1;

					if ($row["startstamp"]!="" && $row["endstamp"]!="") {
						if ($row["startstamp"] > $row["endstamp"]) {
							$arr_error[$row["user_id"]] += 1;
						} elseif ($row["goesstamp"]!="" && $row["backstamp"]=="" || $row["goesstamp"]=="" && $row["backstamp"]!="") {
							$arr_error[$row["user_id"]] += 1;
						} else {
							if ($row["goesstamp"]=="") {
								$startstamp = datetime2timestamp(date("Y-m-d")." ".date("H:i",datetime2timestamp($row["startstamp"])).":00");
								$endstamp = datetime2timestamp(date("Y-m-d")." ".date("H:i",datetime2timestamp($row["endstamp"])).":00");
								$timespan = $endstamp-$startstamp;
								$arr_time[$row["user_id"]] += $timespan;
								$arr_shukkin[$row["user_id"]] += 1;
							} else {
								if ($row["goesstamp"] > $row["endstamp"]) {
									$arr_error[$row["user_id"]] += 1;
								} else {
									$startstamp = datetime2timestamp(date("Y-m-d")." ".date("H:i",datetime2timestamp($row["startstamp"])).":00");
									$endstamp = datetime2timestamp(date("Y-m-d")." ".date("H:i",datetime2timestamp($row["endstamp"])).":00");
									$timespan = $endstamp-$startstamp;

									$backstamp = datetime2timestamp(date("Y-m-d")." ".date("H:i",datetime2timestamp($row["backstamp"])).":00");
									$goesstamp = datetime2timestamp(date("Y-m-d")." ".date("H:i",datetime2timestamp($row["goesstamp"])).":00");
									$timespan = $timespan - ($backstamp-$goesstamp);

									$arr_time[$row["user_id"]] += $timespan;
									$arr_shukkin[$row["user_id"]] += 1;
								}
							}
						}
					} elseif ($row["startstamp"]=="" && $row["endstamp"]=="") {
					} else {
						$arr_error[$row["user_id"]] += 1;
					}
					if ($maxtime<$arr_time[$row["user_id"]]) {
						$maxtime = $arr_time[$row["user_id"]];
					}
				}
			}
		}
		
    // エラー処理
    if (sizeof($MES)>0){
      $pagetext .= "<BR><CENTER><font color=#FF0000><B>";
      while (list($key,$val)=each($MES)) {
        $pagetext .= $val."<BR>";
      }
    } else {
      // 正常処理
      $pagetext .= "<CENTER>";

			$forwarduri = "./?y=$by&m=$bm";
			if (!empty($part_id))  { $forwarduri .= "&part_id=".$part_id; }
			if (!empty($group_id)) { $forwarduri .= "&group_id=".$group_id; }
			if (!empty($user_id))  { $forwarduri .= "&user_id=".$user_id; }
			$pagetext .= "<A HREF=\"$forwarduri\">";
			$pagetext .= "&lt;&lt;";
			$pagetext .= "</A>";

			$pagetext .="&nbsp;";
			$pagetext .=$y."年";
			$pagetext .=$m."月";
			$pagetext .="&nbsp;";

			$nexturi = "./?y=$ny&m=$nm";
			if (!empty($part_id))  { $nexturi .= "&part_id=".$part_id; }
			if (!empty($group_id)) { $nexturi .= "&group_id=".$group_id; }
			if (!empty($user_id))  { $nexturi .= "&user_id=".$user_id; }
			$pagetext .="<A HREF=\"$nexturi\">";
			$pagetext .="&gt;&gt;";
			$pagetext .= "</A>";
		// add by nanbuwks 20111125
    $pagetext .= "<td ALIGN=RIGHT><A HREF=\"./csvoutall.phtml?y=".$y."&m=".$m."\"><IMG SRC=\"../../image/filesadd.gif\" BORDER=0 ALIGN=ABSMIDDLE ALT=\"CSVファイルのダウンロード\">CSVダウ
ンロード</A></td>";
	
			$pagetext .= "<BR><BR>\n";
			
			$pagetext .= "<TABLE CELLSPACING=1 CELLPADDING=4 BORDER=$borderwidth BGCOLOR=#666666>";
			
			if ($cnt==0) {
				$pagetext .= "<TR><TD>";
				$pagetext .= "<CENTER>予定は登録されていません</CENTER>";
				$pagetext .= "</TD></TR>";
			} else {
				asort($arr_seqno);

				$pagetext .= "<TR BGCOLOR=$bg_dark>";
				$pagetext .= "<TD> </TD>";
				$pagetext .= "<TD>ユーザー</TD>";
				$pagetext .= "<TD ALIGN=RIGHT>総時間</TD>";
				$pagetext .= "<TD ALIGN=RIGHT>出勤日数</TD>";
				$pagetext .= "<TD ALIGN=RIGHT>エラー日数</TD>";
				$pagetext .= "<TD ALIGN=RIGHT>平均時間</TD>";
				$pagetext .= "<TD ALIGN=CENTER>　</TD>";
				$pagetext .= "<TD ALIGN=CENTER> 有休 </TD>";
				$pagetext .= "<TD ALIGN=CENTER> 指名休 </TD>";
				$pagetext .= "</TR>";

				while(list($user_id,$num)=each($arr_seqno)) {
					$pagetext .= "<TR BGCOLOR=$bodyBackColor>";
					
					$pagetext .= "<TD>";
					$pagetext .= "<a href=\"./browse.phtml?id=".$user_id."&y=$y&m=$m\">詳細</a>";
					$pagetext .= "</TD>";

					$pagetext .= "<TD>";
					$pagetext .= get_first("users","name_ryaku","id='$user_id'","<FONT COLOR=#FF0000>不明または削除");
					$pagetext .= "</TD>";
					
					$pagetext .= "<TD ALIGN=RIGHT>";
					$times = $arr_time[$user_id];
					if ($times>3600) {
						$hour = floor($times/3600);
						$times = $times % 3600;
						$pagetext .= number_format($hour)."時間";
					}
					if ($times>60) {
						$minuts = floor($times/60);
						$times = $times % 60;
						$pagetext .= number_format($minuts)."分";
					}
					$pagetext .= number_format($times)."秒";
					$pagetext .= "</TD>";
					
					$pagetext .= "<TD ALIGN=RIGHT>";
					$pagetext .= number_format($arr_shukkin[$user_id])."日";
					$pagetext .= "</TD>";
					
					$pagetext .= "<TD ALIGN=RIGHT>";
					$pagetext .= number_format($arr_error[$user_id])."日";
					$pagetext .= "</TD>";

					$pagetext .= "<TD ALIGN=RIGHT>";

					if ($arr_shukkin[$user_id]>0 && $arr_time[$user_id]>0) {
						$times = $arr_time[$user_id]/$arr_shukkin[$user_id];
						if ($times>3600) {
							$hour = floor($times/3600);
							$times = $times % 3600;
							$pagetext .= number_format($hour)."時間";
						}
						if ($times>60) {
							$minuts = floor($times/60);
							$times = $times % 60;
							$pagetext .= number_format($minuts)."分";
						}
#						$pagetext .= number_format($times)."秒";
					} else {
						$pagetext .= "-";
					}
					$pagetext .= "</TD>";

					$pagetext .= "<TD>";
					if ($arr_time[$user_id]>0) {
						$pagetext .= "<TABLE CELLPADDING=1 CELLSPACING=0 BGCOLOR=#000000><TR><TD>";
						$pagetext .= "<TABLE CELLPADDING=0 CELLSPACING=0><TR HEIGHT=12>";
						$pagetext .= "<TD WIDTH=".ceil(220*(double)($arr_time[$user_id]/$maxtime))." BGCOLOR=#0000ff>";
						$pagetext .= "<IMG SRC=\"../../image/null.gif\" HEIGHT=12 WIDTH=".ceil(220*(double)($arr_time[$user_id]/$maxtime)).">";
						$pagetext .= "</TR></TABLE>";
						$pagetext .= "</TD></TR></TABLE>";
					} else {
						$pagetext .= "&nbsp;";
					}
					$pagetext .= "</TD>";
					$pagetext .= "<TD>";
			$sql2 = "select count(seqno) as count from schedules where datefrom >= '".date("Y-m-d",$firststamp)."' and datefrom <= '".date("Y-m-d",$laststamp)."' and  user_id LIKE '".$user_id."' and kind like '5' ;";
			$res2 = pg_query($conn,$sql2);
			$cnt2 = pg_num_rows($res2);
                        if ($cnt2>0) {
                               $row2 = pg_fetch_array($res2);
                               $pagetext .= $row2["count"];
                        }
					$pagetext .= "</TD>";
					$pagetext .= "<TD>";
	
			$sql2 = "select count(seqno) as count from schedules where datefrom >= '".date("Y-m-d",$firststamp)."' and datefrom <= '".date("Y-m-d",$laststamp)."' and  user_id LIKE '".$user_id."' and kind like '1' ;";
			$res2 = pg_query($conn,$sql2);
			$cnt2 = pg_num_rows($res2);
                        if ($cnt2>0) {
                               $row2 = pg_fetch_array($res2);
                               $pagetext .= $row2["count"];
                        }
					$pagetext .= "</TD>";
					$pagetext .= "</TR>";
			}
			
			$pagetext .= "</TABLE>";
			$pagetext .= "</CENTER>";
		}
	}
}	
	include ("../../detail.inc.php");
	include ("../../footer.inc.php");
?>
