<?php
  include "../../config.inc.php"; include "../../lib.inc.php";
	
	if (!empty($_GET["y"])) {
		$headertext .= "Set-Cookie: log_y=".$_GET["y"]."; path=/;\n";
	} else {
		$y = $_COOKIE["log_y"];
	}
	if (!empty($_GET["m"])) {
		$headertext .= "Set-Cookie: log_m=".$_GET["y"]."; path=/;\n";
	} else {
		$m = $_COOKIE["log_m"];
	}
	
	if (is_numeric($y) && is_numeric($m) && checkdate($m,1,$y)) {
		$firststamp = mktime(0, 0, 0, $m, 1, $y);
	} else {
		$firststamp = date2timestamp(date("Y-m",time())."-01");
	}
	
	$by = date("Y",$firststamp);
	$bm = date("m",$firststamp)-1;
	if ($bm<1) {
		$bm = 12;
		$by = $by - 1;
	}
	
	$ny = date("Y",$firststamp);
	$nm = date("m",$firststamp)+1;
	if ($nm > 12){
		$ny = $ny + 1;
		$nm = 1;
	}
	$laststamp = mktime(0, 0, 0, $nm, 1, $ny)-86400;
	
	$rows = 9;
	$p = $_REQUEST["p"];
	if ($p=="") $p = 1;
	
	//現在行(1〜rowcount)
	if($rowpos<1) { $rowpos = 1; }
	
	// リンク用テキストの設定
	$linktext  = "<A HREF=\"../../\" CLASS=\"BAR\">トップページ</A> &gt; ";
	$linktext .= "<A HREF=\"../\" CLASS=\"BAR\">管理者メニュー</A> &gt; ";
	$linktext .= "<FONT COLOR=#FFFF00>予定ログ</FONT> ";
	
	// ヘッダ表示
	$notable = true;
	include ("../../header.inc.php"); include ("../menu.inc.php");
	
	if ($login) {
		if ($admin_sign != 't') {
			$MES[] = "本機能は管理者のみ利用することができます。";
		} else {
			## スケジュール抽出
			$sql = "SELECT user_id,timefrom,timeto,kind FROM schedules WHERE ";
			$sql .= "(datefrom>='".date("Y-m-d",$firststamp)."' AND datefrom<='".date("Y-m-d",$laststamp)."') OR ";
			$sql .= "(dateto>='".date("Y-m-d",$firststamp)."' AND dateto<='".date("Y-m-d",$laststamp)."') OR ";
			$sql .= "(datefrom<='".date("Y-m-d",$firststamp)."' AND dateto>='".date("Y-m-d",$laststamp)."')";
			$sql .= " ORDER BY user_id";
			$res = pg_query($conn,$sql);
			$cnt = pg_num_rows($res);
			
			if ($cnt>0) {
				for ($i=0;$i<$cnt;$i++) {
					$row = pg_fetch_array($res,$i);
					
					$arr_user[$row["user_id"]] += 1;
					if ($row["timefrom"]=="" && $row["timeto"]=="") {
						$timespan = 0;
					} elseif ($row["timefrom"]=="" || $row["timeto"]=="") {
						$timespan = 7200;
					} else {
						$timespan = datetime2timestamp($row["timeto"])-datetime2timestamp($row["timefrom"])-60;
					}
					$arr_time[$row["user_id"]] += $timespan;

					if ($row["kind"]=="") $row["kind"]= 999999;

					$arr_kind[$row["user_id"]][(int)$row["kind"]] += 1;

					if ($maxtime<$arr_time[$row["user_id"]]) {
						$maxtime = $arr_time[$row["user_id"]];
					}
				}
			}
		}
		
    // エラー処理
    if (sizeof($MES)>0){
      $pagetext .= "<BR><CENTER><font color=#FF0000><B>";
      while (list($key,$val)=each($MES)) {
        $pagetext .= $val."<BR>";
      }
    } else {
      // 正常処理
      $pagetext .= "<CENTER>";

			$forwarduri = "./?y=$by&m=$bm";
			if (!empty($part_id))  { $forwarduri .= "&part_id=".$part_id; }
			if (!empty($group_id)) { $forwarduri .= "&group_id=".$group_id; }
			if (!empty($user_id))  { $forwarduri .= "&user_id=".$user_id; }
			$pagetext .= "<A HREF=\"$forwarduri\">";
			$pagetext .= "&lt;&lt;";
			$pagetext .= "</A>";

			$pagetext .="&nbsp;";
			$pagetext .=$y."年";
			$pagetext .=$m."月";
			$pagetext .="&nbsp;";

			$nexturi = "./?y=$ny&m=$nm";
			if (!empty($part_id))  { $nexturi .= "&part_id=".$part_id; }
			if (!empty($group_id)) { $nexturi .= "&group_id=".$group_id; }
			if (!empty($user_id))  { $nexturi .= "&user_id=".$user_id; }
			$pagetext .="<A HREF=\"$nexturi\">";
			$pagetext .="&gt;&gt;";
			$pagetext .= "</A>";
			
			$pagetext .= "<BR><BR>\n";
			
			$pagetext .= "<TABLE CELLSPACING=1 CELLPADDING=4 BORDER=$borderwidth BGCOLOR=#666666>";
			
			if ($cnt==0) {
				$pagetext .= "<TR><TD>";
				$pagetext .= "<CENTER>予定は登録されていません</CENTER>";
				$pagetext .= "</TD></TR>";
			} else {
				arsort($arr_user);

				$pagetext .= "<TR BGCOLOR=$bg_dark>";
				$pagetext .= "<TD>ユーザー</TD>";
				$pagetext .= "<TD ALIGN=RIGHT>総時間</TD>";
				$pagetext .= "<TD ALIGN=RIGHT>件数</TD>";
				$pagetext .= "<TD ALIGN=CENTER>時間</TD>";
				$pagetext .= "<TD ALIGN=CENTER>割合</TD>";
				$pagetext .= "</TR>";

				while(list($user_id,$count)=each($arr_user)) {
					$pagetext .= "<TR BGCOLOR=$bodyBackColor>";
					
					$pagetext .= "<TD>";
					$pagetext .= get_first("users","name_ryaku","id='$user_id'","<FONT COLOR=#FF0000>不明または削除");
					$pagetext .= "</TD>";
					
					$pagetext .= "<TD ALIGN=RIGHT>";
					$times = $arr_time[$user_id];
					if ($times>3600) {
						$hour = floor($times/3600);
						$times = $times % 3600;
						$pagetext .= number_format($hour)."時間";
					}
					if ($times>60) {
						$minuts = floor($times/60);
						$times = $times % 60;
						$pagetext .= number_format($minuts)."分";
					}
					$pagetext .= number_format($times)."秒";
					$pagetext .= "</TD>";
					
					$pagetext .= "<TD ALIGN=RIGHT>";
					$pagetext .= number_format($count)."件";
					$pagetext .= "</TD>";
					
					$pagetext .= "<TD>";
					if ($arr_time[$user_id]>0) {
						$pagetext .= "<TABLE CELLPADDING=1 CELLSPACING=0 BGCOLOR=#000000><TR><TD>";
						$pagetext .= "<TABLE CELLPADDING=0 CELLSPACING=0><TR HEIGHT=12>";
						$pagetext .= "<TD WIDTH=".ceil(150*(double)($arr_time[$user_id]/$maxtime))." BGCOLOR=#cccccc>";
						$pagetext .= "<IMG SRC=\"../../image/null.gif\" HEIGHT=12 WIDTH=".ceil(150*(double)($arr_time[$user_id]/$maxtime)).">";
						$pagetext .= "</TR></TABLE>";
						$pagetext .= "</TD></TR></TABLE>";
					} else {
						$pagetext .= "&nbsp;";
					}
					$pagetext .= "</TD>";

					$pagetext .= "<TD>";
					
					reset($arr_kind);
					$pagetext .= "<TABLE CELLPADDING=1 CELLSPACING=0 BGCOLOR=#000000><TR><TD>";
					$pagetext .= "<TABLE CELLPADDING=0 CELLSPACING=0>";
					$arr_kinds = "";
					while(list($user_id2,$arr)=each($arr_kind)) {
						if ($user_id==$user_id2) {
							while(list($kind_id,$kensu)=each($arr)) {
								$seqno = get_first("schedule_kind","seqno","key=".$kind_id,999999);
								$arr_kinds[(int)$seqno] = $kensu;
							}
						}
					}
					krsort($arr_kinds);

					while(list($seqno,$kensu)=each($arr_kinds)) {
						if ($seqno==999999) {
							$barname = "未選択";
							$barcolor = $bodyBackColor;
						} else {
							$barname = get_first("schedule_kind","value","seqno=".$seqno,"不明または削除");
							$barcolor = get_first("schedule_kind","graphcolor","seqno=".$seqno,"#CCCCCC");
						}
						$pagetext .= "<TR HEIGHT=".ceil($kensu).">";
						$pagetext .= "<TD WIDTH=20 BGCOLOR=$barcolor>";
						$pagetext .= "<IMG SRC=\"../../image/null.gif\" HEIGHT=".ceil($kensu+1)." WIDTH=20 ALT=\"".$barname.":".number_format($kensu)."件\">";
						$pagetext .= "</TD></TR>";
					}
					$pagetext .= "</TABLE>";
					$pagetext .= "</TD></TR></TABLE>";

					$pagetext .= "</TD>";
					
					$pagetext .= "</TR>";
				}
			}
			
			$pagetext .= "</TABLE>";
			$pagetext .= "</CENTER>";
		}
	}
	
	include ("../../detail.inc.php");
	include ("../../footer.inc.php");
?>
