<?php
	include ("../../config.inc.php"); include ("../../lib.inc.php");
	include ("../agent.inc.php"); include ("../emoji.inc.php");

	$pagetitle = "ワークフロー";
	include ("../header.inc.php");

	if (empty($type) || ($type!="to" && $type!="from")) $type = "to";

	if ($login) {
		$txt.= "ワークフロー&emojiok;";
		$txt.= "<hr size=\"0\">";

		// 抽出テーブルの作成
		pg_query($conn, "DELETE FROM t_workflow WHERE session_id='".$sid."'");

		$sql_pre = "SELECT seqno,flow_ids,result_sign FROM workflow WHERE flow_ids ~* '(^|,)".$login_id."(,|$)'";
		$res_pre = pg_query($conn, $sql_pre);
		$cnt_pre = pg_num_rows($res_pre);
		if ($cnt_pre>0) {
			for ($i=0;$i<$cnt_pre;$i++) {
				$row_pre = pg_fetch_array($res_pre,$i);

				// 対象データが必要かどうかの判定処理
				$flow_ids = $row_pre["flow_ids"];
				$flow_arr = preg_split(",",$flow_ids);
				$flow_cnt = sizeof($flow_arr);
				if($flow_cnt>0) {
					for($c=0;$c<$flow_cnt;$c++) {
						if ($flow_arr[$c]==$login_id) {
							$flow_no = $c+1;
							break;
						}
					}
				}

				$status = "0"; //未分類とする

				if ($row_pre["result_sign"]=="") {
					// 承認が完了していないデータ
					$recognize_sign = get_first("workflow_ret","recognize_sign","refno=".$row_pre["seqno"]." AND seqno=".$flow_no,"");
					if ($recognize_sign=="") {
						if ($flow_no==1) {
							$status = "1";
						} else {
							$before_res_cnt = get_count("workflow_ret","refno=".$row_pre["seqno"]." AND seqno=".($flow_no-1));
							if ($before_res_cnt>0) {
								$status = "1";
							}
						}
					} else {
						if ($recognize_sign=="t") {
							$status = "2";
						} elseif ($recognize_sign=="f") {
							$status = "3";
						}
					}
				} elseif ($row_pre["result_sign"]=="t") {
					// 承認されている
					$status = "2";
				} elseif ($row_pre["result_sign"]=="f") {
					// 否認されている
					$status = "3";
				}
				pg_query($conn, "INSERT INTO t_workflow (session_id,seqno,status,createstamp) VALUES ('".$sid."',".$row_pre["seqno"].",'".$status."','now()')");
			}
		}

		// エラーチェック

		// 表示
		if (sizeof($MES) > 0) {
			// エラー
			$txt.= "<FONT color=#FF0000>";
			while (list($key,$val)=each($MES)) { $txt.= $val."<br>"; }
			$txt.= "</FONT>";
		} else {
			// 通常表示
			$sql_cnt = "SELECT status,count(*) as count FROM t_workflow WHERE session_id='$sid' GROUP BY status";
			$res_cnt = pg_query($conn,$sql_cnt);
			$cnt_cnt = pg_num_rows($res_cnt);
			if ($cnt_cnt>0) {
				for($i=0;$i<$cnt_cnt;$i++) {
					$row_cnt = pg_fetch_array($res_cnt,$i);
					if ($row_cnt["status"]=="1") {
						// 未承認のカウント
						$to_not += $row_cnt["count"];
					} elseif ($row_cnt["status"]=="2") {
						// 承認済みのカウント
						$to_has += $row_cnt["count"];
					} elseif ($row_cnt["status"]=="3") {
						// 否認済みのカウント
						$to_has2 += $row_cnt["count"];
					}
				}
			}

			$sql_cnt = "SELECT result_sign,count(*) as count FROM workflow WHERE user_id='$login_id' GROUP BY result_sign";
			$res_cnt = pg_query($conn,$sql_cnt);
			$cnt_cnt = pg_num_rows($res_cnt);
			if ($cnt_cnt>0) {
				for($i=0;$i<$cnt_cnt;$i++) {
					$row_cnt = pg_fetch_array($res_cnt,$i);
					if ($row_cnt["result_sign"]=="") {
						$from_not += $row_cnt["count"];
					} else {
						$from_has += $row_cnt["count"];
					}
				}
			}

			## 受け系か?
			$cnt_master = get_count("flows","user_ids ~* '(^|,)".$login_id."(,|$)'");
			if ($cnt_master>0) {
				// 受信一覧
				$txt.= "&emoji1;<A HREF=\"./list.phtml?type=tonot&ms=$ms&sn=$sn&uid=".$uid."\" accesskey=1>未承認 ";
				if ($to_not > 0) { $txt.= $to_not."件"; } else { $txt.= "なし"; } $txt.= "</A><BR>";
				$txt.= "&emoji2;<A HREF=\"./list.phtml?type=tohas&ms=$ms&sn=$sn&uid=".$uid."\" accesskey=2>承認済 ";
				if ($to_has > 0) { $txt.= $to_has."件"; } else { $txt.= "なし"; } $txt.= "</A><BR>";
				$txt.= "&emoji3;<A HREF=\"./list.phtml?type=tohas2&ms=$ms&sn=$sn&uid=".$uid."\" accesskey=3>否認済 ";
				if ($to_has2 > 0) { $txt.= $to_has2."件"; } else { $txt.= "なし"; } $txt.= "</A><BR>";
			}

			// 送信一覧
			if ($cnt_master>0) {
				$txt.= "&emoji4;";
			} else {
				$txt.= "&emoji1;";
			}
			$txt.= "<A HREF=\"./list.phtml?type=fromnot&ms=$ms&sn=$sn&uid=".$uid."\" accesskey=4>決裁中 ";
			if ($from_not > 0) { $txt.= $from_not."件"; } else { $txt.= "なし"; } $txt.= "</A><BR>";
			if ($cnt_master>0) {
				$txt.= "&emoji5;";
			} else {
				$txt.= "&emoji2;";
			}
			$txt.= "<A HREF=\"./list.phtml?type=fromhas&ms=$ms&sn=$sn&uid=".$uid."\" accesskey=5>決裁済み ";
			if ($from_has > 0) { $txt.= $from_has."件"; } else { $txt.= "なし"; } $txt.= "</A><BR>";
		}
	}
	include ("../footer.inc.php");
?>
