<?php
  /* ヘッダ読み込み */
  include "../../config.inc.php";
  include "../../lib.inc.php";

  // リンク用テキストの設定
  $linktext  = "<A HREF=\"../../\" CLASS=\"BAR\">トップページ</A> &gt; ";
  $linktext .= "<A HREF=\"../\" CLASS=\"BAR\">Webフォルダ</A> &gt; ";
  $linktext .= "<FONT COLOR=#FFFF00>フォルダ作成</FONT> ";

  // 検索機能の使用?
  $search = true;
  $searchuri = "/folder/search/";

  // ヘッダ表示
  include "../../header.inc.php";
  flush();

  if (sizeof($MES)==0) {
    $path    = stripslashes(urldecode($_REQUEST["path"]));
    $addpath = $path;

    // パスの階層チェック
    $addpath = trim($addpath);
    $patharr = preg_split('/',$addpath);
    if (sizeof($patharr)>$path_level) {
      $DMES[] = $path_level."階層以上のフォルダを作成することはできません。";
    }

    if (sizeof($DMES)==0) {
      $pagetext .= "<CENTER><BR>作成したいフォルダ名を入力して作成ボタンを押して下さい <BR><BR>\n";
      $pagetext .= "<TABLE WIDTH=480 BORDER=0 CELLPADDING=4 CELLSPACING=1 BGCOLOR=#999999><TR>\n";
      $pagetext .= "<FORM ACTION=\"./make.phtml\" METHOD=POST>\n";
      $pagetext .= "<INPUT TYPE=HIDDEN NAME=\"uppath\" VALUE=\"".urlencode($addpath)."\">\n";

      $pagetext .= "<TD ALIGN=RIGHT WIDTH=90 NOWRAP VALIGN=TOP BGCOLOR=$td_back_left>カレントフォルダ</TD>\n";
      $pagetext .= "<TD ALIGN=LEFT BGCOLOR=$td_back>$addpath</TD>\n";
#      $pagetext .= "<TD ALIGN=LEFT BGCOLOR=$td_back>".mb_strcut(urldecode($addpath),0,60)."...</TD>\n";
      $pagetext .= "</TR>\n";
      $pagetext .= "<TR>\n";
      $pagetext .= "<INPUT TYPE=HIDDEN NAME=\"addpath\" VALUE=\"$addpath\">\n";
      $pagetext .= "<TD ALIGN=RIGHT WIDTH=90 NOWRAP VALIGN=TOP BGCOLOR=$td_back_left>フォルダ名</TD>\n";
      $pagetext .= "<TD ALIGN=LEFT BGCOLOR=$td_back><INPUT TYPE=TEXT NAME=\"folder\" SIZE=40 STYLE=\"width:220px\"><BR><FONT COLOR=#555555 STYLE=\"COLOR:#FF0000;FONT-SIZE:9pt;LINE-HEIGHT:12pt\">※半角40文字（全角20文字以内）まで</FONT></TD>\n";
      $pagetext .= "</TR>\n";
      $pagetext .= "<TR>\n";
      $pagetext .= "<TD ALIGN=RIGHT WIDTH=90 NOWRAP VALIGN=TOP BGCOLOR=$td_back_left>コメント</TD>\n";
      $pagetext .= "<TD BGCOLOR=$td_back><TEXTAREA NAME=\"comment\" COLS=52 ROWS=5 STYLE=\"width:350px;\">$comment</TEXTAREA></TD>\n";
      $pagetext .= "</TR></TABLE>\n";
      $pagetext .= "<BR>\n";
      $pagetext .= "<INPUT TYPE=SUBMIT VALUE=\"フォルダ作成\" STYLE=\"width:120px\" tabindex=99>\n";
      $pagetext .= "</FORM>\n";
      $pagetext .= "</CENTER>\n";
    } else {
      // エラー表示
      $pagetext .= "<BR><BR>\n";
      $pagetext .= "<CENTER>\n";
      $pagetext .= "<FONT COLOR=#FF0000>\n";
      while (list($key,$val)=each($DMES)) {
        $pagetext .= $val."<BR>\n";
      }
      $pagetext .= "</FONT>\n";
      $pagetext .= "</CENTER>\n";
    }
  }

  // 明細表示
  include "../../detail.inc.php";

  // フッタ表示
  include "../../footer.inc.php";
?>
