<?php
  include ("../../../config.inc.php"); include ("../../../lib.inc.php");
  include ("../../agent.inc.php"); include ("../../emoji.inc.php");

  // ヘッダー出力
  $pagetitle = "施設予約 ";
  if ($s == ""){
    $pagetitle .= "登録";
  } else {
    $sql = "select * from rooms_reserve where seqno=".$s;
    $res = pg_query($conn,$sql);
    if (pg_num_rows($res)>0) {
      $row = pg_fetch_array($res,0);
      $pagetitle .= date("m/d ",date2timestamp($row["date"]));
      $pagetitle .= " ".date("H:i",datetime2timestamp($row["timefrom"]));
      $pagetitle .= "〜";
    }
  }
  include "../../header.inc.php";

  // 前処理
  if ($back=="t") {
    if (!empty($room_id))      { $room_id      = remove_emoji(textsafe(sjis2euc($room_id))); }
    if (!empty($user_id))      { $user_id      = remove_emoji(textsafe(sjis2euc($user_id))); }
    if (!empty($rid))          { $rid          = remove_emoji(textsafe(sjis2euc($rid))); }
    if (!empty($p))            { $p            = remove_emoji(textsafe(sjis2euc($p))); }
    if (!empty($y))            { $y            = remove_emoji(textsafe(sjis2euc($y))); }
    if (!empty($m))            { $m            = remove_emoji(textsafe(sjis2euc($m))); }
    if (!empty($d))            { $d            = remove_emoji(textsafe(sjis2euc($d))); }
    if (!empty($from_y))       { $from_y       = remove_emoji(textsafe(sjis2euc($from_y))); }
    if (!empty($from_m))       { $from_m       = remove_emoji(textsafe(sjis2euc($from_m))); }
    if (!empty($from_d))       { $from_d       = remove_emoji(textsafe(sjis2euc($from_d))); }
    if (!empty($from_hour))    { $from_hour    = remove_emoji(textsafe(sjis2euc($from_hour))); }
    if (!empty($to_minuts))    { $to_minuts    = remove_emoji(textsafe(sjis2euc($to_minuts))); }
    if (!empty($note))         { $note         = remove_emoji(textsafe(sjis2euc($note))); }
    if (!empty($member_count)) { $member_count = remove_emoji(textsafe(sjis2euc($member_count))); }
  } else {
    if (!empty($s)){
      // 編集時
      $type = "edit";
      $sql = "SELECT * FROM rooms_reserve WHERE seqno=$s";
      $res = pg_query($conn,$sql);
      if (pg_num_rows($res)==0) {
        $MES[] = "指定された予約情報は既に削除されています";
      } else {
        $row = pg_fetch_array($res,0);
        $room_id        = $row["room_id"];
        $user_id        = $row["user_id"];
        $create_user_id = $row["create_user_id"];
        $note           = $row["note"];
        $member_count   = $row["member_count"];
        $from_stamp     = date2timestamp($row["date"]);
        $from_y         = date("Y",$from_stamp);
        $from_m         = date("m",$from_stamp);
        $from_d         = date("d",$from_stamp);
        $from           = preg_split(" ",$row["timefrom"]);
        $from_time      = preg_split(":",$from[1]);
        $from_hour      = $from_time[0];
        $from_minuts    = $from_time[1];
        $to             = preg_split(" ",$row["timeto"]);
        $to_time        = preg_split(":",$to[1]);
        $to_hour        = $to_time[0];
        $to_minuts      = $to_time[1];
      }
    } else {
      $type = "new";
      $user_id = $login_id;
      if (!empty($q)) {
        // コピー時
        $sql = "SELECT * FROM rooms_reserve WHERE seqno=$q";
        $res = pg_query($conn,$sql);
        if (pg_num_rows($res)==0) {
          $MES[] = "指定された予約情報は既に削除されています";
        } else {
          $row         = pg_fetch_array($res,0);
          $room_id     = $row["room_id"];
          $user_id     = $login_id;
          $note        = $row["note"];
          $member_count= $row["member_count"];
          $from_stamp  = date2timestamp($row["date"]);
          $from_y      = date("Y",$from_stamp);
          $from_m      = date("m",$from_stamp);
          $from_d      = date("d",$from_stamp);
          $from        = preg_split(" ",$row["timefrom"]);
          $from_time   = preg_split(":",$from[1]);
          $from_hour   = $from_time[0];
          $from_minuts = $from_time[1];
          $to          = preg_split(" ",$row["timeto"]);
          $to_time     = preg_split(":",$to[1]);
          $to_hour     = $to_time[0];
          $to_minuts   = $to_time[1];
        }
      } else {
        // 通常時
        $room_id = $rid;
        $user_id = $login_id;
        $note = "";
        $sql = "SELECT from_h,from_m,to_h,to_m FROM users WHERE id='$login_id'";
        $res = pg_query($conn,$sql);
        $row = pg_fetch_array($res,0);
        if ($row["from_h"]<>""){
          $from_hour   = $row["from_h"];
          $from_minuts = $row["from_m"];
          $to_hour     = $row["to_h"];
          $to_minuts   = $row["to_m"];
        } else {
          $from_hour   = 9;
          $from_minuts = 0;
          $to_hour     = -1;
          $to_minuts   = -1;
        }
        if ($ey=="" or $em=="" or $ed==""){
          $from_y = date("Y",time()+7200);
          $from_m = date("m",time()+7200);
          $from_d = date("d",time()+7200);
          $to_y   = date("Y",time()+7200);
          $to_m   = date("m",time()+7200);
          $to_d   = date("d",time()+7200);
        } else {
          $from_y = $ey;
          $from_m = $em;
          $from_d = $ed;
          $to_y   = $ey;
          $to_m   = $em;
          $to_d   = $ed;
        }
        $member_count = 1;
      }
    }
  }

  if (!empty($room_id)) {
    $manage_id = get_first("rooms","manage_id","id='$room_id'","");
  }

  if (sizeof($MES)==0) {
    // 施設の配列取り込み
    $sql_room = "SELECT rooms.seqno,rooms.id,rooms.name";
    $sql_room.= ",rooms.manage_id,rooms.view_group_ids,rooms.view_user_ids FROM rooms_type";
    $sql_room.= " inner join rooms on rooms_type.seqno=rooms.type";
    $sql_room.= " ORDER BY rooms_type.seqno,rooms.seqno";
    $res_room = pg_query($conn,$sql_room);
    if (pg_num_rows($res_room)>0){
      for ($i=0;$i<pg_num_rows($res_room);$i++){
        $row = pg_fetch_array($res_room,$i);
        $arr_room[$i] = array($row["id"],$row["name"],$row["manage_id"],$row["view_group_ids"],$row["view_user_ids"]);
      }
    } else {
      $MES[] = "施設未登録";
    }
  }

  if (sizeof($MES)>0) {
    // エラーメッセージ出力
    $txt.= "<FONT COLOR=#FF0000>";
    while (list($key,$val)=each($MES)) {
      $txt.= $val."<BR>";
    }
    $txt.= "</FONT>";
  } else {
    // ここから正常処理
    $txt.= "<FORM action=\"./add.phtml\" METHOD=POST>";
    $txt.= "<INPUT TYPE=HIDDEN NAME=\"dummy\" VALUE=\"ShiftJISコードで記述されています\">";
    if (!empty($ms))      { $txt.= "<INPUT TYPE=HIDDEN NAME=\"ms\" VALUE=\"$ms\">"; }
    if (!empty($rid))     { $txt.= "<INPUT TYPE=HIDDEN NAME=\"rid\" VALUE=\"$rid\">"; }
    if (!empty($rid))     { $txt.= "<INPUT TYPE=HIDDEN NAME=\"room_id\" VALUE=\"$room_id\">"; }
    if (!empty($s))       { $txt.= "<INPUT TYPE=HIDDEN NAME=\"seqno\" VALUE=\"$s\">"; }
    if (!empty($p))       { $txt.= "<INPUT TYPE=HIDDEN NAME=\"p\" VALUE=\"$p\">"; }
    if (!empty($y))       { $txt.= "<INPUT TYPE=HIDDEN NAME=\"y\" VALUE=\"$y\">"; }
    if (!empty($m))       { $txt.= "<INPUT TYPE=HIDDEN NAME=\"m\" VALUE=\"$m\">"; }
    if (!empty($d))       { $txt.= "<INPUT TYPE=HIDDEN NAME=\"d\" VALUE=\"$d\">"; }
    if (!empty($user_id)) { $txt.= "<INPUT TYPE=HIDDEN NAME=\"user_id\" VALUE=\"$user_id\">"; }

    if ($user_id == $login_id or $manage_id == $login_id) {
      ## 施設名
      $txt.= "施設:<BR>";
      $txt.= "<SELECT NAME=\"room_id\">";
      while (list($key,$room)=each($arr_room)) {
        $use = false;
        if (empty($room[2]) || $room[2]==$login_id || (empty($room[3]) && empty($room[4]))) {
          $use = true;
        } else {
          if ($room[3]!="") {
            $view_group_id = preg_split(",",$room[3]);
            if (sizeof($view_group_id)>0) while (list($seq,$id)=each($view_group_id)) {
              $chkcnt = get_count("users_entry","user_id='$login_id' AND group_id='$id'");
              if ($chkcnt>0) { $use = true; break; }
            }
          }
          if ($room[4]!="") {
            $view_user_id = preg_split(",",$room[4]);
            if (sizeof($view_user_id)>0) while (list($seq,$id)=each($view_user_id)) {
              if ($login_id==$id) { $use = true; break; }
            }
          }
        }
        if ($use) {
          $txt.= "<OPTION VALUE=\"".$room[0]."\"";
          if ($room[0]==$room_id) $txt.= " SELECTED";
          $txt.= ">".$room[1];
        }
      }
      $txt.= "</SELECT><BR>";

      ## 日付
      $txt.= "日付:<BR>";
      $txt.= "<INPUT TYPE=TEXT NAME=\"from_y\" VALUE=\"$from_y\" SIZE=4 MAXLENGTH=4 ".inputmode("numeric").">";
      if ($char_w>16) { $txt.= "年"; } else { $txt.= "/"; }
      $txt.= "<SELECT NAME=\"from_m\">";
        for ($i=1;$i<=12;$i++){
          $txt.= "<OPTION VALUE=\"$i\"";
          if ($i == $from_m) { $txt.= " SELECTED"; }
          $txt.= ">";
          if (strlen($i)==1) $txt.= "0";
          $txt.= $i;
        }
      $txt.= "</SELECT>";
      if ($char_w>16) { $txt.= "月"; } else { $txt.= "/"; }
      $txt.= "<SELECT NAME=\"from_d\">";
      for ($i=1;$i<=31;$i++){
        $txt.= "<OPTION VALUE=\"$i\"";
        if ($i == $from_d) $txt.= " SELECTED";
        $txt.= ">";
        if (strlen($i)==1) $txt.= "0";
        $txt.= $i;
      }
      $txt.= "</SELECT>";
      if ($char_w>16) $txt.= "日";
      $txt.= "<BR>";

      ## 開始時刻
      $txt.= "開始時刻:<BR>";
      $txt.= "<SELECT NAME=\"from_hour\">";
      $txt.= "<OPTION VALUE=\"-1\"";
      if ($from_hour==-1) $txt.= " SELECTED";
      $txt.= ">--";
      for ($i=0;$i<=23;$i++){
        $txt.= "<OPTION VALUE=\"$i\"";
        if ($i == $from_hour) $txt.= " SELECTED";
        $txt.= ">";
        if (strlen($i)==1) $txt.= "0";
        $txt.= $i;
      }
      $txt.= "</SELECT>時";
      $txt.= "<SELECT NAME=\"from_minuts\">";
      $txt.= "<OPTION value=\"-1\"";
      if ($from_minuts==-1) $txt.= " SELECTED";
      $txt.= ">--";
      for ($i=0;$i<60;$i=$i+$interval){
      $txt.= "<OPTION VALUE=\"$i\"";
        if ($i == $from_minuts) $txt.= " SELECTED";
        $txt.= ">";
        if (strlen($i)==1) $txt.= "0";
        $txt.= $i;
      }
      $txt.= "</SELECT>分<BR>";

      ## 終了時刻
      $txt.= "終了時刻:<BR>";
      $txt.= "<SELECT NAME=\"to_hour\">";
      $txt.= "<OPTION VALUE=\"-1\"";
      if ($to_hour==-1) $txt.= " SELECTED";
      $txt.= ">--";
      for ($i=0;$i<=23;$i++){
        $txt.= "<OPTION VALUE=\"$i\"";
        if ($i == $to_hour) $txt.= " SELECTED";
        $txt.= ">";
        if (strlen($i)==1) $txt.= "0";
        $txt.= $i;
      }
      $txt.= "</SELECT>時";
      $txt.= "<SELECT NAME=\"to_minuts\">";
      $txt.= "<OPTION VALUE=\"-1\"";
      if ($to_minuts==-1) $txt.= " SELECTED";
      $txt.= ">--";
      for ($i=0;$i<60;$i=$i+$interval){
        $txt.= "<OPTION VALUE=\"$i\"";
      if ($i == $to_minuts) $txt.= " SELECTED";
      $txt.= ">";
      if (strlen($i)<=1) $txt.= "0";
        $txt.= $i;
      }
      $txt.= "</SELECT>分<BR>";

      $txt.= "内容:<BR>";
      $txt.= "<TEXTAREA NAME=\"note\" ROWS=3>".mb_convert_kana($note,"ak","EUC-JP")."</TEXTAREA>";
      $txt.= "<BR>";

      $txt.= "利用人数:<BR>";
      $txt.= "<INPUT TYPE=TEXT NAME=\"member_count\" VALUE=\"".$member_count."\" SIZE=3 MAXLENGTH=4 ".inputmode("numeric").">名";

      if ($type != "new"){
        if ($user_id == $login_id or $manage_id == $login_id) {
          $txt.= "<CENTER><INPUT TYPE=SUBMIT VALUE=\"更新\"></CENTER>\n";
          $txt.= "</FORM>";
          $txt.= "<FORM name=\"del\" action=\"../del/\" method=\"post\">";
          $txt.= "<INPUT TYPE=\"HIDDEN\" NAME=\"ms\" VALUE=\"".$ms."\">";
          $txt.= "<INPUT TYPE=\"HIDDEN\" NAME=\"seqno\" VALUE=\"".$s."\">";
          $txt.= "<INPUT type=\"hidden\" name=\"rid\" value=\"".$rid."\">";
          $txt.= "<INPUT type=\"hidden\" name=\"p\" value=\"".$p."\">";
          $txt.= "<INPUT type=\"hidden\" name=\"y\" value=\"".$y."\">";
          $txt.= "<INPUT type=\"hidden\" name=\"m\" value=\"".$m."\">";
          $txt.= "<INPUT type=\"hidden\" name=\"d\" value=\"".$d."\">";
          $txt.= "<CENTER><INPUT TYPE=SUBMIT VALUE=\"削除\"></CENTER>";
          $txt.= "</FORM>";
        }
      } else {
        $txt.= "<CENTER><INPUT TYPE=SUBMIT VALUE=\"登録\"></CENTER>";
        $txt.= "</FORM>";
      }
    } else {
      // 自身のデータ以外の表示
      $txt.= "施設:";
      while (list($key,$room)=each($arr_room)) {
        if ($room[0]==$room_id) {
          $txt.= mb_convert_kana($room[1],"ak","EUC-JP");
          break;
        }
      }
      $txt.= "<BR>";

      $txt.= "利用:";

      $sql_user = "SELECT * FROM users WHERE id='".$user_id."'";
      $res_user = pg_exec($conn,$sql_user);
      $cnt_user = pg_num_rows($res_user);
      if ($cnt_user==0) {
        $txt.= "不明";
      } else {
        $row_user = pg_fetch_array($res_user,0);
        $username = $row_user["name_ryaku"];
        if (trim($username)=="") $username = $row_user["name"];

        if ($user_id == $login_id) {
          $txt.= $username;
        } else {
          $usermail = $row_user["email_sub"];
          if (trim($usermail)=="") $usermail = $row_user["email"];

          $txt.= "<A HREF=\"../../mem/detail.phtml$serial&sn=$sn&id=".$user_id."\">";
          $txt.= $username;
          $txt.= "</A>";

          if (trim($row_user["email_sub"])!="") {
            $txt.= "<A HREF=\"mailto:".$row_user["email_sub"]."\">";
            $txt.= "&emojimobilephone;";
            $txt.= "</A>";
          }
          if (trim($row_user["email"])!="") {
            $txt.= "<A HREF=\"mailto:".$row_user["email"]."\">";
            $txt.= "&emojipc;";
            $txt.= "</A>";
          }
        }
      }
      $txt.= "<BR>";

      $txt.= "日付:";
      $txt.= $from_y."/".$from_m."/".$from_d;
      $txt.= "(".$wname[date("w",$from_stamp)].")";
      $txt.= "<BR>";
      $txt.= "時刻:";
      $txt.= $from_hour.":".$from_minuts."〜".$to_hour.":".$to_minuts;
      $txt.= "<BR>";

      $note = mb_convert_kana($note,"ak","EUC-JP");
      $txt.= "内容:";
      if (strlen($note)>200) {
        $txt.= "<FONT COLOR=#FF0000>文字数オーバー</FONT><BR>";
      }
      $txt.= "";
      if (strlen($note)>200) {
        $txt.= mb_strcut($note,0,200,"EUC-JP");
        $txt.= "<DIV ALIGN=RIGHT>⇒ <A HREF=\"./note.phtml$serial&sn=$sn&rid=$rid&s=$s&p=$p&y=$y&m=$m&d=$d\">全体表示</A></DIV>";
      } else {
        $txt.= $note;
        $txt.= "<BR>";
      }

      $txt.= "人数:".number_format($member_count)."名<BR>";
    }
  }
 include "../../footer.inc.php";
?>
