<?php
  include ("../../../config.inc.php"); include ("../../../lib.inc.php");
  include ("../../agent.inc.php"); include ("../../emoji.inc.php");

  $pagetitle = "リンク登録";
  include ("../../header.inc.php");

  // ログインチェック
  if ($login == false) {
    $MES[] = "先に、ログインしてください ⇒ <A HREF=\"/i/\">ログインページへ</A>";
  } else {
    if (trim($login_id) == "") {
      $MES[] = "ユーザーIDが正しくありません";
    } else {
      $sql = "select * from users where id='".$login_id."'";
      $txt.= "<!--";
      $res = pg_query($conn, $sql);

      if (pg_num_rows($res)<1) {
        $MES[] = "ユーザーIDが正しくありません";
      } else {
        $row = pg_fetch_array($res,0);
      }
      $txt.= "-->";
    }
  }

  if (sizeof($MES) > 0) {
    // エラーメッセージ出力
    $txt.= "<FONT color=#FF0000>"; while (list($key,$val)=each($MES)) { $txt.= $val."<br>"; } $txt.= "</FONT>\n";
#      include ("../footer.inc.php");
    exit;
  } else {
    if ($_POST["mode"]=="back") {
      if (!empty($_REQUEST["sn"])) { $sn = remove_emoji(textsafe(sjis2euc($_REQUEST["sn"]))); }
      if (!empty($_REQUEST["s"])) { $s = remove_emoji(textsafe(sjis2euc($_REQUEST["s"]))); }
      if (!empty($_REQUEST["p"])) { $p = remove_emoji(textsafe(sjis2euc($_REQUEST["p"]))); }
      if (!empty($_REQUEST["t"])) { $t = remove_emoji(textsafe(sjis2euc($_REQUEST["t"]))); }
      if (!empty($_REQUEST["u"])) { $u = remove_emoji(textsafe(sjis2euc($_REQUEST["u"]))); }
    } elseif (!empty($s)){
      ## 編集時
      $sql = "SELECT * FROM links WHERE type='$agenttype' AND keitaisign='t' AND seqno=$s";
      $res = pg_query($conn,$sql);
      if (pg_num_rows($res)>0){
        $row = pg_fetch_array($res,0);
        $t = mb_convert_kana($row["title"],"ak","EUC-JP");
        $u = $row["url"];
      } else {
        $MES[] = "未登録";
      }
    } else {
      ## 新規時
      $t = "";
      $u = "http://";
    }

    $txt.= "<FORM ACTION=\"./add.phtml$serial\" METHOD=POST>";
    if (!empty($sn)) { $txt.= "<INPUT TYPE=HIDDEN NAME=\"ms\" VALUE=\"$ms\">"; }
    if (!empty($s))  { $txt.= "<INPUT TYPE=HIDDEN NAME=\"s\" VALUE=\"$s\">"; }
    if (!empty($p))  { $txt.= "<INPUT TYPE=HIDDEN NAME=\"p\" VALUE=\"$p\">"; }

    ## リンクタイトル
    $txt.= "タイトル:<BR>\n";
    if ($agenttype == "jsky") {
      $txt.= "<TEXTAREA NAME=\"t\" ROWS=1 ".inputmode("hiragana").">$t</TEXTAREA>";
      $txt.= "<BR>";
    } else {
      $txt.= "<INPUT TYPE=TEXT NAME=\"t\" VALUE=\"$t\" ".inputmode("hiragana")."><BR>";
    }

    ## リンクURL
    $txt.= "リンクURL:<BR>\n";
    if ($agenttype == "jsky") {
      $txt.= "<TEXTAREA NAME=\"u\" ROWS=1 ".inputmode("alphabet").">$u</TEXTAREA>";
      $txt.= "<BR>";
    } else {
      $txt.= "<INPUT TYPE=TEXT NAME=\"u\" VALUE=\"$u\" ".inputmode("alphabet")."><BR>";
    }

    ## ボタン関連
    $txt.= "<BR>\n";
    $txt.= "<CENTER>";
    if (empty($s)){
      $txt.= "<INPUT TYPE=SUBMIT VALUE=\"登録\">";
    } else {
      $txt.= "<INPUT TYPE=SUBMIT VALUE=\"更新\">";
    }
    $txt.= "</CENTER>";
    $txt.= "</FORM>";
    if (!empty($s)){
      $txt.= "<FORM ACTION=\"../del/$serial\" METHOD=POST>";
      if (!empty($sn)) { $txt.= "<INPUT TYPE=HIDDEN NAME=\"ms\" VALUE=\"$ms\">"; }
      if (!empty($s))  { $txt.= "<INPUT TYPE=HIDDEN NAME=\"s\" VALUE=\"$s\">"; }
      if (!empty($p))  { $txt.= "<INPUT TYPE=HIDDEN NAME=\"p\" VALUE=\"$p\">"; }
      $txt.= "<CENTER><INPUT TYPE=SUBMIT VALUE=\"削除\"></CENTER>";
      $txt.= "</FORM>";
    }
    $txt.= "<BR>";
  }
	include ("../../footer.inc.php");
?>
