<?php
  /* ヘッダ読み込み */
  include "../../config.inc.php";
  include "../../lib.inc.php";

  // パスなし対策
  $path = stripslashes($_REQUEST["path"]);
  if ($path=="") {
    header("Location: http://".$domain."/folder/");
    exit;
  }
  // リンク用テキストの設定
  $linktext  = "<A HREF=\"../../\"CLASS=\"BAR\">トップページ</A> &gt; ";
  $linktext .= "<A HREF=\"../\" CLASS=\"BAR\">Webフォルダ</A> &gt; ";
  $linktext .= "<FONT COLOR=#FFFF00>フォルダ情報</FONT> ";

  // 検索機能の使用?
  $search    = true;
  $searchuri = "/folder/search/";

  // ヘッダ表示
  include "../../header.inc.php";
  flush();

  if ($login && sizeof($MES)==0) {
    $pagetext  = "";

    // 存在チェック
    $viewpath = $folderpath.$path;
    if (!file_exists($viewpath)) {
      $DMES[] = "指定されたフォルダが見つからないか既に削除されています";
    }

    if (sizeof($DMES) > 0) {
      // エラー時
      $pagetext .= "<BR><CENTER><FONT COLOR=#FF0000><B>";
      while (list($key,$val)=each($DMES)) $pagetext .= $val."<BR>";
      $pagetext .= "";
    } else {
      // 通常

      // パスのコード変換
      $patharr = preg_split("/",$path);

      // パスからサムネイルフォルダ情報の取得
      $sql = "SELECT * FROM folders WHERE path='".db_textsafe($path)."'";
      $res = pg_query($conn,$sql);
      $cnt = pg_num_rows($res);
      if ($cnt>0) {
        $row = pg_fetch_array($res,0);
        $folderno = $row["seqno"];
        if (strlen($folderno)<6) $folderno = str_repeat("0",6-strlen($folderno)).$folderno;
      }

      // ページ作成
      $pagetext .= "
<script language=\"JavaScript\">
<!--
function deleteconf() {
  if (confirm('このフォルダを削除しますか？\\n\\n※ディレクトリ内のファイルは全て先に削除しておいてください')) {
    location.href = './folderdelete.phtml?path=".urlencode($path)."';
  }
}

function selGroup(f) {
  f.group[1].checked = true;
}
function clearGroup(f) {
  for (i=0;i<f.elements.length;i++) {
    if (f.elements[i].name == \"group_ids[]\") {
      var p = i;
      break;
    }
  }
  var o = f.elements[p];
  for (i=0;i<o.length;i++) {
    o.options[i].selected = false;
  }
}
function selUser(f) {
  f.user[1].checked = true;
}
function clearUser(f) {
  for (i=0;i<f.elements.length;i++) {
    if (f.elements[i].name == \"user_ids[]\") {
      var p = i;
      break;
    }
  }
  var o = f.elements[p];
  for (i=0;i<o.length;i++) {
    o.options[i].selected = false;
  }
}

//-->
</script>
<BR><CENTER>
";

      // ファイル数の獲得
      if (file_exists($folderpath.$path)) {
        $handle = opendir($folderpath.$path);
        // 獲得
        while ($file = readdir($handle)) { 
          if ($file != "." && $file != ".." && substr($file,0,1) != "." ) { 
            if (is_file($folderpath.$path."/".$file)) {
              $files[] = $file;
            }
            if (is_dir($folderpath.$path."/".$file)) {
              $dirs[] = $file;
            }
          }
        }
      }
      $filecount = sizeof($files);
      $dircount = sizeof($dirs);

      $imageicon = ext_check($name);
      $folderdate = date("Y年m月d日 H:i",filemtime($folderpath.$path));

      // DBから情報取得
      $sql = "SELECT * FROM folders WHERE path='".db_textsafe($path)."'";
      $res = pg_query($conn,$sql);
      $cnt = pg_num_rows($res);
      if ($cnt==0) {
        $user_name  = "不明";
        $comment    = "&nbsp;";
        $user_ids   = "";
        $group_ids  = "";
      } else {
        $row = pg_fetch_array($res,0);

        $user_name = get_first("users","name_ryaku","id='".$row["user_id"]."'","不明");

        $comment = $row["comment"];
        if (trim($comment)=="") $comment = "<FONT COLOR=#777755>未入力";

        $user_ids  = $row["view_user_ids"];
        $group_ids = $row["view_group_ids"];
      }

      if ($admin_sign=="t" && $path!="/") {
        $pagetext .= "<TABLE WIDTH=480><TR><TD><FONT COLOR=#555555>作成者 : ";
        $pagetext .= "<A HREF=\"../../member/?id=".$row["user_id"]."\">".$user_name."<IMG SRC=\"../../image/clip.gif\" BORDER=0 WIDTH=10 HEIGHT=11 ALIGN=ABSMIDDLE></A>";
        $pagetext .= "</TD></TR></TABLE>\n";
      }

      $user_id = preg_split(",",$user_ids);
      $group_id = preg_split(",",$group_ids);

      $pagetext .= "
<TABLE BORDER=0 CELLPADDING=4 CELLSPACING=1 width=480 BGCOLOR=#999999>
<TR>
<TD ALIGN=RIGHT WIDTH=90 NOWRAP VALIGN=TOP BGCOLOR=$td_back_left>フォルダ名</TD>
<TD ALIGN=LEFT BGCOLOR=$td_back>
<TABLE BORDER=0 CELLPADDING=0 CELLSPACING=0><TR><TD><A HREF=\"../?relpath=".urlencode($path)."\"><IMG SRC=\"../../image/icon/folder.gif\" BORDER=0 ALT=\"フォルダ名 : ".$path."  \n作成日 : ".$folderdate."\" WIDTH=32 HEIGHT=32></A></TD><TD>&nbsp;</TD><TD>$path</TD></TR></TABLE>
</TD>
</TR>
";
      if ($admin_sign=="t" && $dircount>0) {
        $pagetext .= "
<TR>
<TD ALIGN=RIGHT WIDTH=90 NOWRAP VALIGN=TOP BGCOLOR=$td_back_left>フォルダ数</TD>
<TD ALIGN=LEFT BGCOLOR=$td_back>".number_format($dircount)."</TD>
</TR>
";
      }

      if ($filecount>0) {
        $pagetext .= "
<TR>
<TD ALIGN=RIGHT WIDTH=90 NOWRAP VALIGN=TOP BGCOLOR=$td_back_left>ファイル数</TD>
<TD ALIGN=LEFT BGCOLOR=$td_back>".number_format($filecount)."</TD>
</TR>
";
      }

      if ($admin_sign=="t" && $path!="/") {

        $pagetext .= "
<TR>
<TD ALIGN=RIGHT WIDTH=90 NOWRAP VALIGN=TOP BGCOLOR=$td_back_left>利用者設定</TD>
<TD ALIGN=LEFT BGCOLOR=$td_back>
";
        $pagetext .= "<TABLE CELLPADDING=3 CELLSPACING=1 BGCOLOR=#999999>\n";
        $pagetext .= "<TR><TD BGCOLOR=#CCCCCC ALIGN=CENTER>グループ指定</TD>\n";
        $pagetext .= "<TD BGCOLOR=#999999 ALIGN=CENTER>ユーザー指定</TD></TR>\n";
        $pagetext .= "<TR>\n";
        $pagetext .= "<FORM ACTION=\"./chown.phtml\" METHOD=POST>\n";
        $pagetext .= "<INPUT TYPE=HIDDEN NAME=\"target\" VALUE=\"group\">\n";
        $pagetext .= "<INPUT TYPE=HIDDEN NAME=\"path\" VALUE=\"".urlencode($path)."\">\n";
        $pagetext .= "<TD BGCOLOR=$td_back ALIGN=CENTER STYLE=\"text-align:center\">";

        $pagetext .= "<INPUT TYPE=RADIO NAME=\"group\" VALUE=\"all\"";
        if ($group_ids=="" || $group_ids=="all") {
          $pagetext .= " CHECKED";
        }
        $pagetext .= " ONCLICK=\"clearGroup(this.form)\">未設定";

        $pagetext .= "<INPUT TYPE=RADIO NAME=\"group\" VALUE=\"select\"";
        if ($group_ids!="" && $group_ids!="all") {
          $pagetext .= " CHECKED";
        }
        $pagetext .= ">個別選択<BR>\n";

        $pagetext .= "<SELECT NAME=\"group_ids[]\" SIZE=5 MULTIPLE STYLE=\"width:120px\" ONCLICK=\"selGroup(this.form)\">\n";

        $sql_group = "SELECT * FROM groups ORDER BY seqno";
        $res_group = pg_query($conn,$sql_group);
        $cnt_group = pg_num_rows($res_group);
        if ($cnt_group>0) {
          for ($i=0;$i<$cnt_group;$i++) {
            $row_group = pg_fetch_array($res_group,$i);
            $pagetext .= "<OPTION VALUE=\"".$row_group["id"]."\"";
            if (sizeof($group_id)>0) {
              reset($group_id);
              while (list($key,$val)=each($group_id)) {
                if ($val==$row_group["id"]) { $pagetext .= " SELECTED"; break; }
              }
            }
            $pagetext .= ">".$row_group["name"]."\n";
          }
        }

        $pagetext .= "</SELECT><BR>\n";

        $pagetext .= "<INPUT TYPE=SUBMIT VALUE=\"変更\">";

        $pagetext .= "</TD>";
        $pagetext .= "</FORM>\n";

        $pagetext .= "<FORM ACTION=\"./chown.phtml\" METHOD=POST>\n";
        $pagetext .= "<INPUT TYPE=HIDDEN NAME=\"target\" VALUE=\"user\">\n";
        $pagetext .= "<INPUT TYPE=HIDDEN NAME=\"path\" VALUE=\"".urlencode($path)."\">\n";
        $pagetext .= "<TD BGCOLOR=$td_back ALIGN=CENTER STYLE=\"text-align:center\">";

        $pagetext .= "<INPUT TYPE=RADIO NAME=\"user\" VALUE=\"all\"";
        if ($user_ids=="" || $user_ids=="all") {
          $pagetext .= " CHECKED";
        }
        $pagetext .= " ONCLICK=\"clearUser(this.form)\">未設定";

        $pagetext .= "<INPUT TYPE=RADIO NAME=\"user\" VALUE=\"select\"";
        if ($user_ids!="" && $user_ids!="all") {
          $pagetext .= " CHECKED";
        }
        $pagetext .= ">個別選択<BR>\n";

        $pagetext .= "<SELECT NAME=\"user_ids[]\" SIZE=5 MULTIPLE STYLE=\"width:160px\" ONCLICK=\"selUser(this.form)\">\n";

        $sql_user = "SELECT * FROM users ORDER BY seqno";
        $res_user = pg_query($conn,$sql_user);
        $cnt_user = pg_num_rows($res_user);
        if ($cnt_user>0) {
          for ($i=0;$i<$cnt_user;$i++) {
            $row_user = pg_fetch_array($res_user,$i);
            $pagetext .= "<OPTION VALUE=\"".$row_user["id"]."\"";
            if (sizeof($user_id)>0) {
              reset($user_id);
              while (list($key,$val)=each($user_id)) {
                if ($val==$row_user["id"]) { $pagetext .= " SELECTED"; break; }
              }
            }
            $pagetext .= ">".$row_user["name"]."\n";
          }
        }

        $pagetext .= "</SELECT><BR>\n";

        $pagetext .= "<INPUT TYPE=SUBMIT VALUE=\"変更\">";

        $pagetext .= "</TD>";
        $pagetext .= "</FORM>";
        $pagetext .= "</TR></TABLE>\n";
        $pagetext .= "<FONT STYLE=\"font-size:8pt\" COLOR=#777755>※ どちらかの指定に該当することでフォルダが表示されます</FONT>";

        $pagetext .= "
</TD></TR>
";
      }

      if ($path!="/") {
        $pagetext .= "
<TR>
<TD ALIGN=RIGHT WIDTH=90 NOWRAP VALIGN=TOP BGCOLOR=$td_back_left>コメント</TD>
<TD ALIGN=LEFT BGCOLOR=$td_back>$comment</TD>
</TR>
";
      }

      $pagetext .= "
</TABLE>

<TABLE WIDTH=480><TR><TD ALIGN=RIGHT><FONT COLOR=#555555>作成日時 : $folderdate</TD></TR></TABLE>
<BR>
";

      if ($admin_sign=="t" && $path!="/") {
        $pagetext .= "
<TABLE BORDER=0 CELLPADDING=3 CELLSPACING=0 WIDTH=480><TR>
<FORM ACTION=\"./delete.phtml\" METHOD=\"POST\" ONSUBMIT=\"deleteconf()\">
<INPUT TYPE=HIDDEN NAME=\"path\" VALUE=\"$path\">
<TD WIDTH=50% ALIGN=RIGHT><INPUT TYPE=SUBMIT VALUE=\"フォルダの削除\"></TD>
</FORM>
<FORM ACTION=\"./rename.phtml\" METHOD=\"POST\">
<INPUT TYPE=HIDDEN NAME=\"path\" VALUE=\"$path\">
<TD WIDTH=50% ALIGN=LEFT><INPUT TYPE=SUBMIT VALUE=\"フォルダの名称変更\"></TD>
</TR></TABLE>
</FORM>
</CENTER>
";
      }
    }
  }
  // 明細表示
  include "../../detail.inc.php";

  // フッタ表示
  include "../../footer.inc.php";
?>
