<?php
	include ("../../config.inc.php");
	include ("../../lib.inc.php");

	$board = $_COOKIE["board_id"];
	$kwd   = stripslashes(urldecode($_COOKIE["board_kwd"]));

	// リンク用テキストの設定
	$linktext  = "<A HREF=\"../../\" ALT=\"トップページ\" CLASS=\"BAR\">トップページ</A> &gt; ";
	$linktext .= "<A HREF=\"../\" ALT=\"掲示板\" CLASS=\"BAR\">掲示板</A> &gt; ";
	$linktext .= "<FONT COLOR=#FFFF00>新しい発言</FONT> ";

	// 検索機能の使用?
	$search = true;
	$searchuri = "/bulletin/";

	## 変数設定
	$txt = "";
	$pagetext = "";

	## ヘッダ表示
	include ("../../header.inc.php");

	if ($login && sizeof($MES)==0) {
		## 前処理
		$p       = trim(textsafe($_POST["p"]));
		$no      = trim(textsafe($_POST["no"]));
		$body    = trim(textsafe($_POST["body"]));
		$subject = trim(textsafe($_POST["subject"]));
		$parent  = trim(textsafe($_POST["parent"]));

		$sql_board = "SELECT * FROM boards ORDER BY seqno";
		$res_board = pg_query($conn,$sql_board);
		$cnt_board = pg_num_rows($res_board);
		if ($cnt_board==0) $DMES[] = "掲示板が作成されていません";

		if (sizeof($DMES)==0) {
			$txt.= "<BR>\n";
			$txt.= "<CENTER>\n";
			$txt.= "タイトルと本文を入力して、投稿ボタンをクリックしてください。<BR><BR>\n";
			$txt.= "<TABLE BORDER=0 CELLPADDING=4 CELLSPACING=1 width=480 BGCOLOR=#999999>\n";
			$txt.= "<FORM ACTION=\"./check.phtml\" METHOD=POST>\n";
			$txt.= "<INPUT TYPE=HIDDEN NAME=\"p\" VALUE=\"".$p."\">\n";
			$txt.= "<INPUT TYPE=HIDDEN NAME=\"parent\" VALUE=\"".$parent."\">\n";

			$txt.= "<TR>\n";
			$txt.= "<TD ID=\"list_h01\">掲示板</TD>\n";
			$txt.= "<TD ALIGN=LEFT BGCOLOR=$td_back>\n";
			if (empty($parent)) {
				## 投稿が許可されている掲示板表示
				$txt.= "<SELECT NAME=\"board\">\n";
				if ($cnt_board>0) {
					for ($i=0;$i<$cnt_board;$i++) {
						$use = false;
						$row_board = pg_fetch_array($res_board,$i);
						$manage_id  = $row_board["admin_id"];
						$boardsid   = $row_board["id"];
						$boardsname = $row_board["name"];
						$group_ids  = $row_board["view_group_ids"];
						$user_ids   = $row_board["view_user_ids"];
						if ($manage_id==$login_id || ($group_ids=="" && $user_ids=="")) {
							## 管理者 or 掲示板管理者 or 制約のない掲示板
							$use = true;
						} else {
							if ($group_ids!="") {
								$view_group_id = preg_split(",",$group_ids);
								if (sizeof($view_group_id)>0) while (list($seq,$id)=each($view_group_id)) {
									$chkcnt = get_count("users_entry","user_id='$login_id' AND group_id='$id'");
									if ($chkcnt>0) { $use = true; break; }
								}
							}
							if ($user_ids!="") {
								$view_user_id = preg_split(",",$user_ids);
								if (sizeof($view_user_id)>0) while (list($seq,$id)=each($view_user_id)) {
									if ($login_id==$id) { $use = true; break; }
								}
							}
						}
						if ($use) {
							$txt.= "<OPTION VALUE=\"".$boardsid."\"";
							if ((empty($board) && $i==0) || (!empty($board) && $board == $boardsid)) $txt.= " SELECTED";
							$txt.= ">";
							$txt.= $boardsname;
							$txt.= "</OPTION>\n";
						}
					}
				}
				$txt.= "</SELECT>\n";
			} else {
				$boardsname = get_first("boards","name","id='".$board."'","");
				$txt.= $boardsname;
				$txt.= "<INPUT TYPE=HIDDEN NAME=\"board\" VALUE=\"".$board."\">\n";
			}
			$txt.= "</TD>\n";
			$txt.= "</TR>\n";

			$txt.= "<TR>\n";
			$txt.= "<TD ID=\"list_h01\">タイトル</TD>\n";
			$txt.= "<TD ALIGN=LEFT BGCOLOR=$td_back>\n";
			$txt.= "<INPUT TYPE=TEXT SIZE=46 NAME=\"subject\" VALUE=\"$subject\"></TD>\n";
			$txt.= "</TR>\n";

			$txt.= "<TR>\n";
			$txt.= "<TD ID=\"list_h01\">本文</TD>\n";
			$txt.= "<TD ALIGN=LEFT BGCOLOR=$td_back>\n";
			if (!empty($no) && is_numeric($no)) {
				$b_body = get_first("boards_post","body","board_id='".$board."' AND seqno=$no","");
				$b_bodys = preg_split("\n",$b_body);
				while(list($seq,$line)=each($b_bodys)) {
					$body .= "> ".$line."\n";
				}
			}
			$txt.= "<TEXTAREA NAME=\"body\" COLS=52 ROWS=15 STYLE=\"width:380px;height:200px\">".$body."</TEXTAREA>\n";
			$txt.= "</TD></TR>\n";

			## 返信通知
			$txt.= "<TR>\n";
			$txt.= "<TD ID=\"list_h01\">返信通知</TD>\n";
			$txt.= "<TD ALIGN=LEFT BGCOLOR=$td_back>\n";
			if ($replysign=="t") {
				$txt.= "<INPUT TYPE=RADIO NAME=\"replysign\" VALUE=\"t\" CHECKED><FONT COLOR=#3333FF>あり</FONT>\n";
				$txt.= "<INPUT TYPE=RADIO NAME=\"replysign\" VALUE=\"f\"><FONT COLOR=#FF3333>なし</FONT><BR>\n";
			} else {
				$txt.= "<INPUT TYPE=RADIO NAME=\"replysign\" VALUE=\"t\"><FONT COLOR=#3333FF>あり</FONT>\n";
				$txt.= "<INPUT TYPE=RADIO NAME=\"replysign\" VALUE=\"f\" CHECKED><FONT COLOR=#FF3333>なし</FONT><BR>\n";
			}
			$txt.= "<FONT STYLE=\"FONT-SIZE:7pt\">※ この投稿に対する返信があった場合、メールにて通知されます</FONT>";
			$txt.= "</TD></TR>\n";
			$txt.= "</TABLE>\n";

			$txt.= "<BR>\n";
			$txt.= "<INPUT TYPE=SUBMIT VALUE=\"発言を確認する\" STYLE=\"width:140px\">\n";
			$txt.= "</FORM>\n";

			$txt.= "</CENTER>\n";

		} else {
			// エラー時
			$txt.= "<BR><BR>\n";
			$txt.= "<CENTER>\n";
			$txt.= "<FONT COLOR=#FF0000>\n";
			while (list($key,$val)=each($DMES)) {
				$txt.= $val."<BR>\n";
			}
			$txt.= "</FONT>\n";
			$txt.= "<BR><FORM ACTION=\"./\" METHOD=POST>\n";
			$txt.= "<INPUT TYPE=BUTTON VALUE=\"戻る\" ONCLICK=\"history.back()\">\n";
			$txt.= "</FORM>\n";
			$txt.= "</CENTER>\n";
		}
		$pagetext = $txt;
	}

	include "../../detail.inc.php";
	include "../../footer.inc.php";
?>